# Schema for the configuration files of the custom_logger module.
custom_logger.settings:
  type: config_object
  label: 'custom_logger settings'
  mapping:
    example:
      type: string
      label: 'Example'
