<?php

/**
 * @file
 * Primary module hooks for custom_mail module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_mail().
 */

function custom_mail_mail($key, &$message, $params){
    $options= array(
        'langcode' => $message ['langcode'],
    );
    switch($key){
        case 'create_page';
          $message['from'] = \Drupal::config('system.site')->get('mail');
          $message['subject'] = t('Page created: @title', array('@title' => $params['node_title']), $options);
          $message['body'][] = $params['message'];
          break;
         
    }
}

/**
 * Implements hook_entity_insert().
 */

function custom_mail_entity_insert(Drupal\Core\Entity\EntityInterface $entity){
    if($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId()=== 'node' && $entity->bundle() !== 'page')){
        return;
    }

    $mailManager = \Drupal::service('plugin.manager.mail');

    $module = 'custom_mail';
    $key = 'create_page';
    $to = \Drupal::currentUser()->getEmail();
    $params['message'] = $entity->get('body')->value;
    $params['node_title'] = $entity->label();
    $langcode= \Drupal::currentUser()->getPreferredLangcode();
    $send = true;

    $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);

    if($result['result'] !== true){
        \Drupal::messenger()->addMessage(t('There was problem in sending mail'),'error');
    }
    else{
        \Drupal::messenger()->addMessage(t('Mail send successfully'),'status');
    }

}